export interface Currency {
  code: string;
  name: string;
  flagUrl: string;
  symbol: string;
}

export interface ExchangeRates {
  [key: string]: number;
}

export const SUPPORTED_CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar', flagUrl: 'https://flagcdn.com/us.svg', symbol: '$' },
  { code: 'EUR', name: 'Euro', flagUrl: 'https://flagcdn.com/eu.svg', symbol: '€' },
  { code: 'GBP', name: 'British Pound', flagUrl: 'https://flagcdn.com/gb.svg', symbol: '£' },
  { code: 'JPY', name: 'Japanese Yen', flagUrl: 'https://flagcdn.com/jp.svg', symbol: '¥' },
  { code: 'CAD', name: 'Canadian Dollar', flagUrl: 'https://flagcdn.com/ca.svg', symbol: 'CA$' },
  { code: 'AUD', name: 'Australian Dollar', flagUrl: 'https://flagcdn.com/au.svg', symbol: 'A$' },
  { code: 'CHF', name: 'Swiss Franc', flagUrl: 'https://flagcdn.com/ch.svg', symbol: 'CHF' },
  { code: 'CNY', name: 'Chinese Yuan', flagUrl: 'https://flagcdn.com/cn.svg', symbol: 'CN¥' },
  { code: 'INR', name: 'Indian Rupee', flagUrl: 'https://flagcdn.com/in.svg', symbol: '₹' },
  { code: 'BRL', name: 'Brazilian Real', flagUrl: 'https://flagcdn.com/br.svg', symbol: 'R$' },
  { code: 'MXN', name: 'Mexican Peso', flagUrl: 'https://flagcdn.com/mx.svg', symbol: '$' },
  { code: 'ZAR', name: 'South African Rand', flagUrl: 'https://flagcdn.com/za.svg', symbol: 'R' },
  { code: 'SGD', name: 'Singapore Dollar', flagUrl: 'https://flagcdn.com/sg.svg', symbol: 'S$' },
  { code: 'HKD', name: 'Hong Kong Dollar', flagUrl: 'https://flagcdn.com/hk.svg', symbol: 'HK$' },
  { code: 'NZD', name: 'New Zealand Dollar', flagUrl: 'https://flagcdn.com/nz.svg', symbol: 'NZ$' },
  { code: 'KRW', name: 'South Korean Won', flagUrl: 'https://flagcdn.com/kr.svg', symbol: '₩' },
  { code: 'TRY', name: 'Turkish Lira', flagUrl: 'https://flagcdn.com/tr.svg', symbol: '₺' },
  { code: 'RUB', name: 'Russian Ruble', flagUrl: 'https://flagcdn.com/ru.svg', symbol: '₽' },
  { code: 'SEK', name: 'Swedish Krona', flagUrl: 'https://flagcdn.com/se.svg', symbol: 'kr' },
  { code: 'NOK', name: 'Norwegian Krone', flagUrl: 'https://flagcdn.com/no.svg', symbol: 'kr' },
  { code: 'DKK', name: 'Danish Krone', flagUrl: 'https://flagcdn.com/dk.svg', symbol: 'kr' },
  { code: 'PLN', name: 'Polish Zloty', flagUrl: 'https://flagcdn.com/pl.svg', symbol: 'zł' },
  { code: 'THB', name: 'Thai Baht', flagUrl: 'https://flagcdn.com/th.svg', symbol: '฿' },
  { code: 'IDR', name: 'Indonesian Rupiah', flagUrl: 'https://flagcdn.com/id.svg', symbol: 'Rp' },
  { code: 'MYR', name: 'Malaysian Ringgit', flagUrl: 'https://flagcdn.com/my.svg', symbol: 'RM' },
  { code: 'PHP', name: 'Philippine Peso', flagUrl: 'https://flagcdn.com/ph.svg', symbol: '₱' },
  { code: 'ILS', name: 'Israeli New Shekel', flagUrl: 'https://flagcdn.com/il.svg', symbol: '₪' },
  { code: 'AED', name: 'UAE Dirham', flagUrl: 'https://flagcdn.com/ae.svg', symbol: 'د.إ' },
  { code: 'SAR', name: 'Saudi Riyal', flagUrl: 'https://flagcdn.com/sa.svg', symbol: '﷼' },
  { code: 'EGP', name: 'Egyptian Pound', flagUrl: 'https://flagcdn.com/eg.svg', symbol: 'E£' },
  { code: 'VND', name: 'Vietnamese Dong', flagUrl: 'https://flagcdn.com/vn.svg', symbol: '₫' },
  { code: 'ARS', name: 'Argentine Peso', flagUrl: 'https://flagcdn.com/ar.svg', symbol: '$' },
  { code: 'CLP', name: 'Chilean Peso', flagUrl: 'https://flagcdn.com/cl.svg', symbol: '$' },
  { code: 'COP', name: 'Colombian Peso', flagUrl: 'https://flagcdn.com/co.svg', symbol: '$' },
  { code: 'PEN', name: 'Peruvian Sol', flagUrl: 'https://flagcdn.com/pe.svg', symbol: 'S/' },
  { code: 'CZK', name: 'Czech Koruna', flagUrl: 'https://flagcdn.com/cz.svg', symbol: 'Kč' },
  { code: 'HUF', name: 'Hungarian Forint', flagUrl: 'https://flagcdn.com/hu.svg', symbol: 'Ft' },
  { code: 'RON', name: 'Romanian Leu', flagUrl: 'https://flagcdn.com/ro.svg', symbol: 'lei' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', flagUrl: 'https://flagcdn.com/ua.svg', symbol: '₴' },
  { code: 'KWD', name: 'Kuwaiti Dinar', flagUrl: 'https://flagcdn.com/kw.svg', symbol: 'KD' },
  { code: 'QAR', name: 'Qatari Rial', flagUrl: 'https://flagcdn.com/qa.svg', symbol: 'QR' },
  { code: 'OMR', name: 'Omani Rial', flagUrl: 'https://flagcdn.com/om.svg', symbol: 'RO' },
  { code: 'BHD', name: 'Bahraini Dinar', flagUrl: 'https://flagcdn.com/bh.svg', symbol: 'BD' },
  { code: 'TWD', name: 'New Taiwan Dollar', flagUrl: 'https://flagcdn.com/tw.svg', symbol: 'NT$' },
  { code: 'PKR', name: 'Pakistani Rupee', flagUrl: 'https://flagcdn.com/pk.svg', symbol: '₨' },
  { code: 'KZT', name: 'Kazakhstani Tenge', flagUrl: 'https://flagcdn.com/kz.svg', symbol: '₸' },
  { code: 'IQD', name: 'Iraqi Dinar', flagUrl: 'https://flagcdn.com/iq.svg', symbol: 'ع.د' },
  { code: 'DZD', name: 'Algerian Dinar', flagUrl: 'https://flagcdn.com/dz.svg', symbol: 'د.ج' },
  { code: 'MAD', name: 'Moroccan Dirham', flagUrl: 'https://flagcdn.com/ma.svg', symbol: 'د.م.' },
  { code: 'TND', name: 'Tunisian Dinar', flagUrl: 'https://flagcdn.com/tn.svg', symbol: 'د.ت' },
  { code: 'NGN', name: 'Nigerian Naira', flagUrl: 'https://flagcdn.com/ng.svg', symbol: '₦' },
  { code: 'KES', name: 'Kenyan Shilling', flagUrl: 'https://flagcdn.com/ke.svg', symbol: 'KSh' },
  { code: 'GHS', name: 'Ghanaian Cedi', flagUrl: 'https://flagcdn.com/gh.svg', symbol: 'GH₵' },
  { code: 'UGX', name: 'Ugandan Shilling', flagUrl: 'https://flagcdn.com/ug.svg', symbol: 'USh' },
  { code: 'TZS', name: 'Tanzanian Shilling', flagUrl: 'https://flagcdn.com/tz.svg', symbol: 'TSh' },
  { code: 'ETB', name: 'Ethiopian Birr', flagUrl: 'https://flagcdn.com/et.svg', symbol: 'Br' },
  { code: 'LKR', name: 'Sri Lankan Rupee', flagUrl: 'https://flagcdn.com/lk.svg', symbol: 'Rs' },
  { code: 'BDT', name: 'Bangladeshi Taka', flagUrl: 'https://flagcdn.com/bd.svg', symbol: '৳' },
  { code: 'NPR', name: 'Nepalese Rupee', flagUrl: 'https://flagcdn.com/np.svg', symbol: 'Rs' },
  { code: 'MMK', name: 'Myanmar Kyat', flagUrl: 'https://flagcdn.com/mm.svg', symbol: 'K' },
  { code: 'KHR', name: 'Cambodian Riel', flagUrl: 'https://flagcdn.com/kh.svg', symbol: '៛' },
  { code: 'LAK', name: 'Lao Kip', flagUrl: 'https://flagcdn.com/la.svg', symbol: '₭' },
  { code: 'MNT', name: 'Mongolian Tugrik', flagUrl: 'https://flagcdn.com/mn.svg', symbol: '₮' },
  { code: 'UZS', name: 'Uzbekistani Som', flagUrl: 'https://flagcdn.com/uz.svg', symbol: 'so\'m' },
];
